---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  labels:
    app.kubernetes.io/managed-by: fluxcd
provisioner: kubernetes.io/manual
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
