---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  # labels:
  #   app.kubernetes.io/managed-by: git
provisioner: kubernetes.io/manual
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
