---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 5m
  dependsOn:
  - name: loki
    namespace: observability
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 3.9.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    extraArgs:
    - -client.external-labels=hostname=$(HOSTNAME)
    - -config.expand-env

    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
                cluster: k3s
            relabel_configs:
              - source_labels: ['__journal__systemd_unit']
                target_label: 'unit'
              - source_labels: ['__journal__hostname']
                target_label: 'hostname'
              - source_labels: ['__journal_syslog_identifier']
                target_label: syslog_identifier
          - job_name: dmesg
            static_configs:
              - targets: [localhost]
                labels:
                  job: dmesg
                  __path__: /var/log/kern.log
                  # hostname: ${HOSTNAME}
                  cluster: k3s
      file: |
        server:
          log_level: {{ .Values.config.logLevel }}
          http_listen_port: {{ .Values.config.serverPort }}

        clients:
          - url: {{ tpl .Values.config.lokiAddress . }}
            {{- tpl .Values.config.snippets.extraClientConfigs . | nindent 4 }}
          - url: ${SECRET_LOKI_ADDRESS}
            basic_auth:
              username: ${SECRET_LOKI_BASIC_AUTH_USERNAME}
              password: ${SECRET_LOKI_BASIC_AUTH_PASSWORD}
            tls_config:
              insecure_skip_verify: true

        positions:
          filename: /run/promtail/positions.yaml

        scrape_configs:
          {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
          {{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}
    extraVolumes:
    - name: journal
      hostPath:
        path: /var/log/journal
    - name: dmesg
      hostPath:
        path: /var/log/kern.log
    extraVolumeMounts:
    - name: journal
      mountPath: /var/log/journal
      readOnly: true
    - name: dmesg
      mountPath: /var/log/kern.log
      readOnly: true
    serviceMonitor:
      enabled: true
    tolerations:
    - effect: NoSchedule
      operator: Exists
