---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-java-data
  labels:
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/name: minecraft-java
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: ${SECRET_NFS_IP}
    path: /volume1/minecraft-java
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
