---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-java-data
  namespace: gaming
  labels:
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/name: minecraft-java
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: minecraft-java-data
  storageClassName: manual
