---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: gaming
spec:
  interval: 5m
  releaseName: minecraft-bedrock
  # targetNamespace: gaming  # default
  # storageNamespace: gaming  # default
  dependsOn:
  - name: nfs-subdir-external-provisioner
    namespace: storage
  # timeout: 5m  # default
  # maxHistory: 10  # default
  chart:
    spec:
      chart: minecraft-bedrock
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
  values:
    image: itzg/minecraft-bedrock-server
    imageTag: latest

    extraEnv:
      TZ: ${SETTING_TZ}

    persistence:
      storageClass: nas-nfs
      dataDir:
        enabled: true
        Size: 10Gi

    resources:
      requests:
        memory: 1024Mi
        cpu: 2000m

    minecraftServer:
      eula: "TRUE"
      version: "1.18.1.02"
      difficulty: easy
      gameMode: survival
      levelSeed: ""
      ops: "2535405985178539"
      levelName: "cliffs_caves_adventure"
      maxThreads: 0 # Maximum number of threads the server tries to use. If set to 0 or removed then it uses as many as possible.
      cheats: true
      serverName: "Cliffs and Caves"
      serviceType: LoadBalancer

    nodeSelector:
      kubernetes.io/arch: amd64
    #   node-role.kubernetes.io/application: "true"
