---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-bedrock
  namespace: games
spec:
  interval: 5m
  releaseName: minecraft-bedrock
  # targetNamespace: games  # default
  # storageNamespace: games  # default
  dependsOn:
  - name: nfs-subdir-external-provisioner
    namespace: storage
  # timeout: 5m  # default
  # maxHistory: 10  # default
  chart:
    spec:
      chart: minecraft-bedrock
      version: 1.1.9
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
        reconcileStrategy: ChartVersion
  values:
    image: itzg/minecraft-bedrock-server
    imageTag: latest

    extraEnv:
      TZ: ${SETTING_TZ}

    persistence:
      storageClass: nas-nfs
      dataDir:
        enabled: true
        Size: 10Gi

    resources:
      requests:
        memory: 512Mi
        cpu: 500m

    minecraftServer:
      eula: "TRUE"
      version: "1.17.11.01"
      difficulty: hard
      gameMode: survival
      levelSeed: "107016"
      ops: "2535405985178539"
      levelName: "jungle_fever"
      maxThreads: 0 # Maximum number of threads the server tries to use. If set to 0 or removed then it uses as many as possible.
      cheats: true
      serverName: "Jungle Fever"
      serviceType: LoadBalancer

    nodeSelector:
      kubernetes.io/arch: amd64
    #   node-role.kubernetes.io/application: "true"
