---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - notifications
  - helm-repos
  - cluster-settings.yaml
  - cluster-secrets.yaml
  # - core.yaml
  # - apps.yaml
