---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gaming/minecraft-bedrock
  - gaming/minecraft-java
  - home/home-assistant
  - home/node-red
  - hardware/scanservjs
  # - observability/grafana
  - observability/kube-prometheus-stack
  - observability/alertmanager-discord
  - observability/promtail
  - observability/loki
