---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  namespace: home
  labels:
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/name: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: home-assistant-data
  storageClassName: manual
