---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanservjs-scans
  labels:
    app.kubernetes.io/name: scanservjs
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: ${SECRET_NFS_IP}
    path: /volume1/scans
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
