---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanservjs-scans
  namespace: hardware
  labels:
    app.kubernetes.io/name: scanservjs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: scanservjs-scans
  storageClassName: manual
