---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plans.upgrade.cattle.io
spec:
  group: upgrade.cattle.io
  names:
    plural: plans
    singular: plan
    kind: Plan
    listKind: PlanList
    categories:
      - upgrade
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - upgrade
              properties:
                channel:
                  type: string
                concurrency:
                  type: integer
                cordon:
                  type: boolean
                drain:
                  type: object
                  properties:
                    deleteLocalData:
                      type: boolean
                      nullable: true
                    disableEviction:
                      type: boolean
                    force:
                      type: boolean
                    gracePeriod:
                      type: integer
                      nullable: true
                    ignoreDaemonSets:
                      type: boolean
                      nullable: true
                    skipWaitForDeleteTimeout:
                      type: integer
                    timeout:
                      type: integer
                      nullable: true
                  nullable: true
                nodeSelector:
                  type: object
                  properties:
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                            nullable: true
                      nullable: true
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                      nullable: true
                  nullable: true
                prepare:
                  type: object
                  properties:
                    args:
                      type: array
                      items:
                        type: string
                      nullable: true
                    command:
                      type: array
                      items:
                        type: string
                      nullable: true
                    image:
                      type: string
                  nullable: true
                secrets:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                  nullable: true
                serviceAccountName:
                  type: string
                tolerations:
                  type: array
                  items:
                    type: object
                    properties:
                      effect:
                        type: string
                      key:
                        type: string
                      operator:
                        type: string
                      tolerationSeconds:
                        type: integer
                        nullable: true
                      value:
                        type: string
                  nullable: true
                upgrade:
                  type: object
                  properties:
                    args:
                      type: array
                      items:
                        type: string
                      nullable: true
                    command:
                      type: array
                      items:
                        type: string
                      nullable: true
                    image:
                      type: string
                  nullable: true
                version:
                  type: string
            status:
              type: object
              properties:
                applying:
                  type: array
                  items:
                    type: string
                  nullable: true
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        type: string
                      lastUpdateTime:
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                  nullable: true
                latestHash:
                  type: string
                latestVersion:
                  type: string
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
